spring:
  security:
    oauth2:
      client:
        registration:
          axis:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, profile
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            # According to spec https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1
            # "The authorization server MUST support the HTTP Basic authentication scheme
            # for authenticating clients that were issued a client password."
            # You do not support it.
            redirect-uri: ${REDIRECT_URI}
        provider:
          axis:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            jwk-set-uri: ${JWK_SET_URI}
            user-name-attribute: sub

  datasource:
    url: ${DATASOURCE_URL}
    driverClassName: org.h2.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update

